import { articlesOtherSwiper } from "./swipers/_articles-other-swiper";
import { assemblySwiper } from "./swipers/_assembly-swiper";
import { discountsOtherSwiper } from "./swipers/_discounts-other-swiper";
import { newModelsSwiper } from "./swipers/_new-models-swiper";
import { offerSwiper } from "./swipers/_offer-swiper";
import { productCardSwiper } from "./swipers/_product-card-swiper";
import { productInfoSwiper } from "./swipers/_product-info-swiper";
import { releasedSwiper } from "./swipers/_product-released-swiper";
import { stockSwiper } from "./swipers/_stock-swiper";
import { styleSwiper } from "./swipers/_style-swiper";

offerSwiper();
newModelsSwiper();
productCardSwiper();
productInfoSwiper();
stockSwiper();
assemblySwiper();
styleSwiper();
releasedSwiper();
articlesOtherSwiper();
discountsOtherSwiper();