import './_libs';
import './_swipers';
import './_functions';
import './_components';
import './_header';
import './_text-hidden';
import './_product-page'
import './_froze-page'
import './_company-page'
import './_contacts-page'
import './_production-page'
import './_article-page'
import './_review-page'
